"""Reference-page generator for the deck. Imported by build_references.py.

ADSE requires a references section and does not count it against the
15-page cap, so the pages written here carry `data-refs="1"` and the PDF
build counts them separately. Generating them from SOURCES.md means the
deck can never cite a figure the register does not have.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DECK = ROOT / "deck" / "index.html"
START = "<!-- REFS:START — generated by scripts/build_references.py; do not hand-edit -->"
END = "<!-- REFS:END -->"


def esc(t: str) -> str:
    return t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _page(inner: list, n: int, total: int) -> list:
    of = f" ({n} of {total})" if total > 1 else ""
    head = [
        '<section class="pg refs" data-refs="1">',
        f'  <div class="scope">References{of}</div>',
        "  <h1>Every figure, with its source and its scope</h1>",
    ]
    if n == 1:
        head.append(
            '  <p class="lede">Scope is stated for each figure because several August 2026 '
            "numbers in circulation are national totals that read like local ones. Anything "
            "marked <b>Philippines, national</b> is not Olongapo's.</p>"
        )
    return head + ['  <div class="cols2">'] + inner + [
        "  </div>",
        '  <div class="src">All datasets and the scripts that build them are in the project '
        "repository. Every derived figure regenerates from source with a single command, so any "
        "number on any page can be traced back to the data it came from.</div>",
        "</section>",
    ]


def _group_block(title: str, items: list) -> list:
    out = [f"    <h3>{esc(title)}</h3>", "    <ul>"]
    out += items
    out.append("    </ul>")
    return out


def write_deck_pages(grouped: dict, order: list, rules: list) -> None:
    if not DECK.exists():
        return

    blocks = []  # (weight, lines)
    for org in order:
        if org not in grouped:
            continue
        items = []
        for s in grouped[org]:
            meta = [f"Source: {esc(s['source'])}"]
            if s["published"] and s["published"] != "—":
                meta.append(f"Published: {esc(s['published'])}")
            meta.append(f"Retrieved: {esc(s['retrieved'])}")
            items.append(
                f'      <li><span class="id">[{esc(s["id"])}]</span> {esc(s["figure"])}<br>'
                f'<span class="sc">Scope: {esc(s["scope"])}.</span> '
                f'<span class="mt">{" · ".join(meta)}</span></li>'
            )
        blocks.append((len(grouped[org]), _group_block(org, items)))

    if rules:
        items = [
            f'      <li><span class="id">[{esc(r["id"])}]</span> {esc(r["rule"])}<br>'
            f'<span class="mt">{esc(r["source"])} · Retrieved: {esc(r["retrieved"])}</span></li>'
            for r in rules
        ]
        blocks.append((len(rules), _group_block("Competition rules consulted", items)))

    # Two pages. References are exempt from the 15-page cap, so there is no
    # reason to cram: at one page, ten of twenty-six citations overflowed the
    # column box and were clipped without any visible sign.
    total = sum(w for w, _ in blocks)
    half, run, first, second = total / 2, 0, [], []
    for w, lines in blocks:
        if run < half or not first:
            first += lines
            run += w
        else:
            second += lines

    body = _page(first, 1, 2) + _page(second, 2, 2)

    html = DECK.read_text(encoding="utf-8")
    i, j = html.index(START), html.index(END)
    nl = chr(10)
    html = html[: i + len(START)] + nl + nl.join(body) + nl + html[j:]
    DECK.write_text(html, encoding="utf-8")
    print(f"  injected 2 reference pages into {DECK.relative_to(ROOT)}")
